# Generated by Django 5.1.2 on 2024-11-26 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GFG',
        ),
    ]
