# Generated by Django 5.1.2 on 2024-11-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_program_customuser_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.ManyToManyField(blank=True, to='accounts.program'),
        ),
    ]
