# Generated by Django 5.1.2 on 2024-11-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_is_active_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='program',
            field=models.ManyToManyField(to='accounts.program'),
        ),
    ]
