# Generated by Django 5.1.2 on 2024-11-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_program_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='profile/wbm-logo.png', upload_to='profile'),
        ),
    ]
