# Generated by Django 5.1.2 on 2024-11-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_image_alter_student_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='student_image/wbm-logo.png', null=True, upload_to='student_image'),
        ),
    ]
