# Generated by Django 5.1.2 on 2024-11-27 13:16

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_student_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='student_image/wbm-logo.png', null=True, upload_to='avatars'),
        ),
    ]
